//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int Id_funcionario { get; set; }
        public string nome { get; set; }
        public string sobre_nome { get; set; }
        public string e_mail { get; set; }
        public string rg { get; set; }
        public string cpf { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string uf { get; set; }
        public Nullable<int> id_departamento { get; set; }
    }
}
